name: cloud-keeper


services:
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    container_name: minio
    volumes:
      - ./data/minio:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"