spring:
  application:
    name: cloud-keeper
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: validate

server:
  servlet:
    context-path: /api/v1/



minio:
  client:
    endpoint: ${MINIO_ENDPOINT}
    user: ${MINIO_ROOT_USER}
    password: ${MINIO_ROOT_PASSWORD}
  bucket-name: user-uploads
