spring:
  application:
    name: cloud-keeper
    user-space-size: 500MB
  config:
    import:
      - optional:file:dev.env[.properties]
      - optional:file:.env[.properties]
  profiles:
    active: dev
    group:
      dev:
        - "auth"
        - "minio"
        - "web"
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  liquibase:
    enabled: true
  data:
    redis:
      password: ${REDIS_PASSWORD}
      port: ${REDIS_PORT}
  session:
    redis:
      repository-type: default
    timeout: 1800
  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: validate
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true


server:
  servlet:
    context-path: /api/v1/
    session:
      cookie:
        secure: true
  tomcat:
    max-swallow-size: 200MB


validation:
  patterns:
    username: "[a-zA-Z0-9@_.]{4,50}"
    password: "[a-zA-Z0-9@_.!#$%^&*]{4,50}"
    objname: (?=.*\S)[\w\!\-\*'\(\)\s]{1,40}
    search: .*\S+.*
  messages:
    username: "Allowed letters, numbers and symbols @_., minimum 4 characters"
    password: "Allowed latin letters, numbers and symbols @_.!#$%^&*, minimum 4 characters."
    objname: "Allowed alphanumeric characters and symbols: !-_*'(). Max length is 40 (at least 1 non-whitespace character)."
    search: "Search query must contain at least 1 non-whitespace character"


minio:
  client:
    endpoint: ${MINIO_ENDPOINT}
    user: ${MINIO_ROOT_USER}
    password: ${MINIO_ROOT_PASSWORD}
  bucket-name: user-files
