spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: test
    password: testpass
  data:
    redis:
      password: testpass
      port: 6379

---
# Configuration for clean MinioServiceTest
spring:
  config:
    activate:
      on-profile: "test & minio"
  liquibase:
    enabled: false
  data:
    redis:
      repositories:
        enabled: false
    jpa:
      repositories:
        enabled: false
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

minio:
  client:
    endpoint: http://localhost:9000
    user: test
    password: testpass

