spring:
  application:
    name: cloud-keeper
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  liquibase:
    enabled: true
  data:
    redis:
      password: ${REDIS_PASSWORD}
      port: ${REDIS_PORT}
  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: validate
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  session:
    redis:
      repository-type: default
    timeout: 1800

server:
  servlet:
    context-path: /api/v1/
    session:
      cookie:
        secure: true


minio:
  client:
    endpoint: ${MINIO_ENDPOINT}
    user: ${MINIO_ROOT_USER}
    password: ${MINIO_ROOT_PASSWORD}
  bucket-name: user-files
  max-listed-objects: 20
