spring:
  application:
    name: cloud-keeper
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: validate


server:
  servlet:
    context-path: /api/v1/
