
spring:
  session:
    timeout: 10


---
# Configuration for clean MinioServiceTest
spring:
  config:
    activate:
      on-profile: "test & minio & !dev"
  liquibase:
    enabled: false
  data:
    redis:
      repositories:
        enabled: false
    jpa:
      repositories:
        enabled: false
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

minio:
  client:
    endpoint: http://localhost:9000
    user: test
    password: testpass

