global:
  scrape_interval: 15s
scrape_configs:
    - job_name: 'spring-app'
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets:
          - spring-app:8080
      basic_auth:
        username: 'prometheus'
        password_file: '/etc/prometheus_password.txt'
