
name: Deploy on a remote server
on:
  workflow_run:
    workflows: [Java tests with Gradle]
    types:
      - completed

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    environment:
      name: production
    env:
      SPRING_DATASOURCE_URL: $ {{ secrets.SPRING_DATASOURCE_URL }}
      SPRING_DATASOURCE_DB: $ {{ secrets.SPRING_DATASOURCE_DB }}
      SPRING_DATASOURCE_USERNAME: $ {{ secrets.SPRING_DATASOURCE_USERNAME }}
      SPRING_DATASOURCE_PASSWORD: $ {{ secrets.SPRING_DATASOURCE_PASSWORD }}
      REDIS_HOST: $ {{ secrets.REDIS_HOST }}
      REDIS_PORT: $ {{ secrets.REDIS_PORT }}
      REDIS_PASSWORD: $ {{ secrets.REDIS_PASSWORD }}
      MINIO_ENDPOINT: $ {{ secrets.MINIO_ENDPOINT }}
      MINIO_ROOT_USER: $ {{ secrets.MINIO_ROOT_USER }}
      MINIO_ROOT_PASSWORD: $ {{ secrets.MINIO_ROOT_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run docker compose
        run: |
          ls -la &&
          cd ${{ secrets.PROJECT_FOLDER }} &&
          git checkout main &&
          git pull &&
          docker-compose -f ./compose-prod.yaml down &&
          docker compose -f ./compose-prod.yaml up -d --build &&
          docker system prune --all --force

