
name: Java tests with Gradle

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment:
      name: test
    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/test
      SPRING_DATASOURCE_DB: test
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: testpass
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      REDIS_PASSWORD: testpass
      MINIO_ENDPOINT: http://localhost:9000
      MINIO_ROOT_USER: test
      MINIO_ROOT_PASSWORD: testpass
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Test with Gradle Wrapper
        run: ./gradlew test

